version: 1.0.{build}-beta
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
platform: Any CPU
init:
- ps: if(-not $env:APPVEYOR_PULL_REQUEST_NUMBER) { $env:is_not_pr = "true"; }
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: dotnet restore src
build:
  project: src/Paillave.Etl.sln
  verbosity: minimal
test:
  assemblies:
    only:
    - src\Paillave.EtlTests\bin\Release\netcoreapp2.1\Paillave.EtlTests.dll
    - src\Paillave.Etl.TextFileTests\bin\Release\netcoreapp2.1\Paillave.Etl.TextFileTests.dll
artifacts:
- path: src\Paillave.Etl\bin\$(configuration)\*.nupkg
  name: Paillave.Etl
- path: src\Paillave.Etl.EntityFrameworkCore\bin\$(configuration)\*.nupkg
  name: Paillave.Etl.EntityFrameworkCore
- path: src\Paillave.Etl.ExecutionPlan\bin\$(configuration)\*.nupkg
  name: Paillave.Etl.ExecutionPlan
- path: src\Paillave.Etl.TextFile\bin\$(configuration)\*.nupkg
  name: Paillave.Etl.TextFile
- path: src\Paillave.Etl.ExcelFile\bin\$(configuration)\*.nupkg
  name: Paillave.Etl.ExcelFile
- path: src\Paillave.Etl.SqlServer\bin\$(configuration)\*.nupkg
  name: Paillave.Etl.SqlServer
- path: src\Paillave.Etl.Ftp\bin\$(configuration)\*.nupkg
  name: Paillave.Etl.Ftp
deploy:
- provider: NuGet
  api_key:
    secure: UgPSmSDViCSpE60+tlJDDe+ocxa2hm7ESlbze7yeh1jE0nFfS0QD71I0JipJ3fbG
  artifact: Paillave.Etl
  on:
    branch: master
    is_not_pr: true
- provider: NuGet
  api_key:
    secure: UgPSmSDViCSpE60+tlJDDe+ocxa2hm7ESlbze7yeh1jE0nFfS0QD71I0JipJ3fbG
  artifact: Paillave.Etl.EntityFrameworkCore
  on:
    branch: master
    is_not_pr: true
- provider: NuGet
  api_key:
    secure: UgPSmSDViCSpE60+tlJDDe+ocxa2hm7ESlbze7yeh1jE0nFfS0QD71I0JipJ3fbG
  artifact: Paillave.Etl.ExecutionPlan
  on:
    branch: master
    is_not_pr: true
- provider: NuGet
  api_key:
    secure: UgPSmSDViCSpE60+tlJDDe+ocxa2hm7ESlbze7yeh1jE0nFfS0QD71I0JipJ3fbG
  artifact: Paillave.Etl.TextFile
  on:
    branch: master
    is_not_pr: true
- provider: NuGet
  api_key:
    secure: UgPSmSDViCSpE60+tlJDDe+ocxa2hm7ESlbze7yeh1jE0nFfS0QD71I0JipJ3fbG
  artifact: Paillave.Etl.ExcelFile
  on:
    branch: master
    is_not_pr: true
- provider: NuGet
  api_key:
    secure: UgPSmSDViCSpE60+tlJDDe+ocxa2hm7ESlbze7yeh1jE0nFfS0QD71I0JipJ3fbG
  artifact: Paillave.Etl.SqlServer
  on:
    branch: master
    is_not_pr: true
- provider: NuGet
  api_key:
    secure: UgPSmSDViCSpE60+tlJDDe+ocxa2hm7ESlbze7yeh1jE0nFfS0QD71I0JipJ3fbG
  artifact: Paillave.Etl.Ftp
  on:
    branch: master
    is_not_pr: true
notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/24499395a6cd92120c65
  method: POST
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
