version: 1.0.{build}-alpha
branches:
  only:
  - develop
image: Visual Studio 2017
configuration: Release
platform: Any CPU
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: dotnet restore src
build:
  project: src/Paillave.Etl.sln
  verbosity: minimal
test:
  assemblies:
    only:
    - src\Paillave.EtlTests\bin\Release\netcoreapp2.2\Paillave.EtlTests.dll
    - src\Paillave.Etl.TextFileTests\bin\Release\netcoreapp2.2\Paillave.Etl.TextFileTests.dll
    - src\Paillave.Etl.XmlFileTests\bin\Release\netcoreapp2.2\Paillave.Etl.XmlFileTests.dll
    - src\Paillave.Etl.EntityFrameworkCoreTests\bin\Release\netcoreapp2.2\Paillave.Etl.EntityFrameworkCoreTests.dll
    - src\Paillave.Etl.Recipes\bin\Release\netcoreapp2.2\Paillave.Etl.Recipes.dll