version: 1.0.{build}-alpha
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
platform: Any CPU
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: dotnet restore src
build:
  project: src/Paillave.Etl.sln
  verbosity: minimal
test:
  assemblies:
    only:
    - src\Paillave.EtlTests\bin\Release\netcoreapp2.1\Paillave.EtlTests.dll
    - src\Paillave.Etl.TextFileTests\bin\Release\netcoreapp2.1\Paillave.Etl.TextFileTests.dll
    - src\Paillave.Etl.TextFileTests\bin\Release\netcoreapp2.1\Paillave.Etl.XmlFileTests.dll
